<?php

use App\Location\City;
use App\Location\Country;
use Illuminate\Database\Seeder;

class CountriesStatesCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $souhtAfrica = Country::create([
            'sortname' => 'ZA',
            'name' => 'South Africa',
        ]);
        $souhtAfrica->save();

        $ec =  $souhtAfrica->states()->create([
            'name' => 'Eastern Cape'
        ]);
        $this->EcCities($ec);

        $fs =  $souhtAfrica->states()->create([
            'name' => 'Free State'
        ]);
        $this->FsCities($fs);

        $gauteng =  $souhtAfrica->states()->create([
            'name' => 'Gauteng'
        ]);
        $this->GautengCities($gauteng);

        $kzn =  $souhtAfrica->states()->create([
            'name' => 'KwaZulu-Natal'
        ]);
        $this->KznCities($kzn);

        $mpn =  $souhtAfrica->states()->create([
            'name' => 'Mpumalanga'
        ]);
        $this->MpnCities($mpn);

        $lmp =  $souhtAfrica->states()->create([
            'name' => 'Limpopo Province'
        ]);
        $this->LmpCities($lmp);

        $nw =  $souhtAfrica->states()->create([
            'name' => 'North West Province'
        ]);
        $this->NwCities($nw);

        $nc =  $souhtAfrica->states()->create([
            'name' => 'Northern Cape'
        ]);
        $this->NcCities($nc);

        $wp =  $souhtAfrica->states()->create([
            'name' => 'Western Cape'
        ]);
        $this->WpCities($wp);
    }

    /**
     * @param $ec
     */
    public function EcCities($ec)
    {
        $ec->cities()->saveMany([
            new City(['name' => 'Adelaide']),
            new City(['name' => 'Alice']),
            new City(['name' => 'Aliwal North']),
            new City(['name' => 'Balfour']),
            new City(['name' => 'Berlin']),
            new City(['name' => 'Bhisho']),
            new City(['name' => 'Braunschweig']),
            new City(['name' => 'Burgersdorp']),
            new City(['name' => 'Cathcart']),
            new City(['name' => 'Dohne']),
            new City(['name' => 'Dordrecht']),
            new City(['name' => 'East London']),
            new City(['name' => 'Elliot']),
            new City(['name' => 'Fort Beaufort']),
            new City(['name' => 'Gonubie']),
            new City(['name' => 'Haga-Haga']),
            new City(['name' => 'Hamburg']),
            new City(['name' => 'Hogsback']),
            new City(['name' => 'Hofmeyr']),
            new City(['name' => 'Katberg']),
            new City(['name' => 'Kei Mouth']),
            new City(['name' => 'Keiskammahoek']),
            new City(['name' => 'Kidds Beach']),
            new City(['name' => 'King William\'s Town']),
            new City(['name' => 'Komga']),
            new City(['name' => 'Mdantsane']),
            new City(['name' => 'Mhlangeni']),
            new City(['name' => 'Molteno']),
            new City(['name' => 'Morgan\'s Bay']),
            new City(['name' => 'Ngcobo']),
            new City(['name' => 'Oyster Bay']),
            new City(['name' => 'Peddie']),
            new City(['name' => 'Queenstown']),
            new City(['name' => 'Seymour']),
            new City(['name' => 'Stutterheim']),
            new City(['name' => 'Tarkastad']),
            new City(['name' => 'Venterstad']),
            new City(['name' => 'Whittlesea']),
            new City(['name' => 'Zwelitsha']),
            new City(['name' => 'Aberdeen']),
            new City(['name' => 'Addo']),
            new City(['name' => 'Alexandria']),
            new City(['name' => 'Bathurst']),
            new City(['name' => 'Bedford']),
            new City(['name' => 'Cookhouse']),
            new City(['name' => 'Cradock']),
            new City(['name' => 'Despatch']),
            new City(['name' => 'Enon']),
            new City(['name' => 'Graaff Reinet']),
            new City(['name' => 'Grahamstown']),
            new City(['name' => 'Hankey']),
            new City(['name' => 'Humansdorp']),
            new City(['name' => 'Jeffreys Bay']),
            new City(['name' => 'Joubertina']),
            new City(['name' => 'Kareedouw']),
            new City(['name' => 'Kenton-on-Sea']),
            new City(['name' => 'Kirkwood']),
            new City(['name' => 'Krakeelrivier']),
            new City(['name' => 'Middelburg']),
            new City(['name' => 'Nieu-Bethesda']),
            new City(['name' => 'Patensie']),
            new City(['name' => 'Paterson']),
            new City(['name' => 'Port Alfred']),
            new City(['name' => 'Port Elizabeth']),
            new City(['name' => 'Salem']),
            new City(['name' => 'Somerset East']),
            new City(['name' => 'St Francis Bay']),
            new City(['name' => 'Steynsburg, Eastern Cape']),
            new City(['name' => 'Steytlerville']),
            new City(['name' => 'Uitenhage']),
            new City(['name' => 'Willowmore']),
        ]);
    }

    /**
     * @param $fs
     * @return mixed
     */
    public function FsCities($fs)
    {
        return $fs->cities()->saveMany([
            new City(['name' => 'Arlington, Free State']),
            new City(['name' => 'Bethlehem']),
            new City(['name' => 'Clarens']),
            new City(['name' => 'Clocolan']),
            new City(['name' => 'Cornelia']),
            new City(['name' => 'Excelsior']),
            new City(['name' => 'Ficksburg']),
            new City(['name' => 'Fouriesburg']),
            new City(['name' => 'Harrismith']),
            new City(['name' => 'Hobhouse']),
            new City(['name' => 'Kestell']),
            new City(['name' => 'Ladybrand']),
            new City(['name' => 'Lindley']),
            new City(['name' => 'Marquard']),
            new City(['name' => 'Memel']),
            new City(['name' => 'Paul Roux']),
            new City(['name' => 'Petrus Steyn']),
            new City(['name' => 'Phuthaditjhaba']),
            new City(['name' => 'Reitz']),
            new City(['name' => 'Rosendal']),
            new City(['name' => 'Senekal']),
            new City(['name' => 'Steynsrus']),
            new City(['name' => 'Swinburne']),
            new City(['name' => 'Tweespruit']),
            new City(['name' => 'Van Reenen']),
            new City(['name' => 'Vrede']),
            new City(['name' => 'Warden']),
            new City(['name' => 'Winburg']),
            new City(['name' => 'Allanridge']),
            new City(['name' => 'Boshof']),
            new City(['name' => 'Bothaville']),
            new City(['name' => 'Brandfort']),
            new City(['name' => 'Bultfontein']),
            new City(['name' => 'Dealesville']),
            new City(['name' => 'Hennenman']),
            new City(['name' => 'Hertzogville']),
            new City(['name' => 'Hoopstad']),
            new City(['name' => 'Kgotsong']),
            new City(['name' => 'Kutlwanong']),
            new City(['name' => 'Makeleketla']),
            new City(['name' => 'Odendaalsrus']),
            new City(['name' => 'Theunissen']),
            new City(['name' => 'Ventersburg']),
            new City(['name' => 'Verkeerdevlei']),
            new City(['name' => 'Virginia']),
            new City(['name' => 'Welkom']),
            new City(['name' => 'Wesselsbron']),
            new City(['name' => 'Winburg']),
            new City(['name' => 'Deneysville']),
            new City(['name' => 'Edenville']),
            new City(['name' => 'Frankfort']),
            new City(['name' => 'Heilbron']),
            new City(['name' => 'Koppies']),
            new City(['name' => 'Kroonstad']),
            new City(['name' => 'Oranjeville']),
            new City(['name' => 'Parys']),
            new City(['name' => 'Sasolburg']),
            new City(['name' => 'Tweeling']),
            new City(['name' => 'Viljoenskroon']),
            new City(['name' => 'Villiers']),
            new City(['name' => 'Vredefort']),
            new City(['name' => 'Bethulie']),
            new City(['name' => 'Bloemfontein']),
            new City(['name' => 'Botshabelo']),
            new City(['name' => 'Dewetsdorp']),
            new City(['name' => 'Edenburg']),
            new City(['name' => 'Fauresmith']),
            new City(['name' => 'Itumeleng']),
            new City(['name' => 'Jacobsdal']),
            new City(['name' => 'Jagersfontein']),
            new City(['name' => 'Koffiefontein']),
            new City(['name' => 'Luckhoff']),
            new City(['name' => 'Mangaung']),
            new City(['name' => 'Petrusburg']),
            new City(['name' => 'Philippolis']),
            new City(['name' => 'Reddersburg']),
            new City(['name' => 'Rouxville']),
            new City(['name' => 'Smithfield']),
            new City(['name' => 'Springfontein']),
            new City(['name' => 'Thaba Nchu']),
            new City(['name' => 'Trompsburg']),
            new City(['name' => 'Van Stadensrus']),
            new City(['name' => 'Wepener']),
            new City(['name' => 'Zastron']),
        ]);
    }

    /**
     * @param $gauteng
     */
    public function GautengCities($gauteng)
    {
        $gauteng->cities()->saveMany([
            new City(['name' => 'Alexandra']),
            new City(['name' => 'Johannesburg']),
            new City(['name' => 'Lenasia']),
            new City(['name' => 'Midrand']),
            new City(['name' => 'Roodepoort']),
            new City(['name' => 'Sandton']),
            new City(['name' => 'Soweto']),
            new City(['name' => 'Mshongo']),
            new City(['name' => 'Klipfontienview']),
            new City(['name' => 'Orange Farm']),
            new City(['name' => 'Alberton']),
            new City(['name' => 'Germiston']),
            new City(['name' => 'Benoni']),
            new City(['name' => 'Boksburg']),
            new City(['name' => 'Brakpan']),
            new City(['name' => 'Clayville']),
            new City(['name' => 'Daveyton']),
            new City(['name' => 'Devon']),
            new City(['name' => 'Duduza']),
            new City(['name' => 'Edenvale']),
            new City(['name' => 'Ennerdale']),
            new City(['name' => 'Germiston']),
            new City(['name' => 'Impumelelo']),
            new City(['name' => 'Isando']),
            new City(['name' => 'Katlehong']),
            new City(['name' => 'Kempton Park']),
            new City(['name' => 'KwaThema']),
            new City(['name' => 'Nigel']),
            new City(['name' => 'Olifantsfontein']),
            new City(['name' => 'Reiger Park']),
            new City(['name' => 'Springs']),
            new City(['name' => 'Tembisa']),
            new City(['name' => 'Thokoza']),
            new City(['name' => 'Tsakane']),
            new City(['name' => 'Vosloorus']),
            new City(['name' => 'Wattville']),
            new City(['name' => 'Atteridgeville']),
            new City(['name' => 'Bronberg']),
            new City(['name' => 'Bronkhorstspruit']),
            new City(['name' => 'Centurion']),
            new City(['name' => 'Cullinan']),
            new City(['name' => 'Ekangala']),
            new City(['name' => 'Ga-Rankuwa']),
            new City(['name' => 'Hammanskraal']),
            new City(['name' => 'Irene']),
            new City(['name' => 'Mabopane']),
            new City(['name' => 'Mamelodi']),
            new City(['name' => 'Pretoria']),
            new City(['name' => 'Rayton']),
            new City(['name' => 'Refilwe']),
            new City(['name' => 'Soshanguve']),
            new City(['name' => 'Zithobeni']),
            new City(['name' => 'Boipatong']),
            new City(['name' => 'Bophelong']),
            new City(['name' => 'Evaton']),
            new City(['name' => 'Sebokeng']),
            new City(['name' => 'Sharpeville']),
            new City(['name' => 'Vanderbijlpark']),
            new City(['name' => 'Vereeniging']),
            new City(['name' => 'Meyerton']),
            new City(['name' => 'Heidelberg']),
            new City(['name' => 'Ratanda']),
            new City(['name' => 'Carletonville']),
            new City(['name' => 'Khutsong']),
            new City(['name' => 'Fochville']),
            new City(['name' => 'Kokosi']),
            new City(['name' => 'Greenspark']),
            new City(['name' => 'Wedela']),
            new City(['name' => 'Welverdiend']),
            new City(['name' => 'Blybank']),
            new City(['name' => 'Chamdor']),
            new City(['name' => 'Dan Pienaarville']),
            new City(['name' => 'Delporton']),
            new City(['name' => 'Factoria']),
            new City(['name' => 'Hekpoort']),
            new City(['name' => 'Kagiso']),
            new City(['name' => 'Kenmare']),
            new City(['name' => 'Kromdraai']),
            new City(['name' => 'Krugersdorp']),
            new City(['name' => 'Munsieville South']),
            new City(['name' => 'Magaliesburg']),
            new City(['name' => 'Monument']),
            new City(['name' => 'Muldersdrift']),
            new City(['name' => 'Munsieville']),
            new City(['name' => 'Noordheuwel']),
            new City(['name' => 'Rangeview']),
            new City(['name' => 'Silverfields']),
            new City(['name' => 'Tarlton']),
            new City(['name' => 'Randfontei']),
            new City(['name' => 'Aureus']),
            new City(['name' => 'Bhongweni']),
            new City(['name' => 'Botha AH']),
            new City(['name' => 'Brandvlei']),
            new City(['name' => 'Culemborg Park']),
            new City(['name' => 'Delmas']),
            new City(['name' => 'Dwarskloof AH']),
            new City(['name' => 'Eikepark']),
            new City(['name' => 'Eland SH']),
            new City(['name' => 'Finsbury']),
            new City(['name' => 'Green Hills']),
            new City(['name' => 'Groot-Elandsvlei AH']),
            new City(['name' => 'Hectorton']),
            new City(['name' => 'Helikon Park']),
            new City(['name' => 'Hillside AH']),
            new City(['name' => 'Home Lake']),
            new City(['name' => 'Kocksoord']),
            new City(['name' => 'Loumarina AH']),
            new City(['name' => 'Middelvlei AH']),
            new City(['name' => 'Millside']),
            new City(['name' => 'Mohlakeng']),
            new City(['name' => 'Mohlakeng Ext 1']),
            new City(['name' => 'Mohlakeng Ext 3']),
            new City(['name' => 'Mohlakeng Ext 4']),
            new City(['name' => 'Mohlakeng Ext 7']),
            new City(['name' => 'Panvlak Gold Mine']),
            new City(['name' => 'Pelzvale AH']),
            new City(['name' => 'Randfontein']),
            new City(['name' => 'Randfontein Estate Gold Mine']),
            new City(['name' => 'Randfontein Harmony Gold Mine']),
            new City(['name' => 'Randfontein NU']),
            new City(['name' => 'Randfontein South AH']),
            new City(['name' => 'Randgate']),
            new City(['name' => 'Randpoort']),
            new City(['name' => 'Rikasrus AH']),
            new City(['name' => 'Robin Park']),
            new City(['name' => 'Tenacre AH']),
            new City(['name' => 'Toekomsrus']),
            new City(['name' => 'West Porges']),
            new City(['name' => 'Westergloor']),
            new City(['name' => 'Wheatlands AH']),
            new City(['name' => 'Wilbotsdal AH']),
            new City(['name' => 'Zenzele']),
            new City(['name' => 'Utiliy Economics']),
            new City(['name' => 'Bekkersdal']),
            new City(['name' => 'Westonaria']),
        ]);
    }

    /**
     * @param $kzn
     */
    public function KznCities($kzn)
    {
        $kzn->cities()->saveMany([
            new City(['name' => 'Charlestown']),
            new City(['name' => 'Dannhauser']),
            new City(['name' => 'Hattingspruit']),
            new City(['name' => 'Madadeni']),
            new City(['name' => 'Newcastle']),
            new City(['name' => 'Utrecht']),
            new City(['name' => 'Osizweni']),
            new City(['name' => 'Amanzimtoti']),
            new City(['name' => 'Cato Ridge']),
            new City(['name' => 'Doonside']),
            new City(['name' => 'Drummond']),
            new City(['name' => 'Durban']),
            new City(['name' => 'ekuPhakameni']),
            new City(['name' => 'Hillcrest']),
            new City(['name' => 'Illovo Beach']),
            new City(['name' => 'Inanda']),
            new City(['name' => 'Isipingo']),
            new City(['name' => 'Karridene']),
            new City(['name' => 'Kingsburgh']),
            new City(['name' => 'Kloof']),
            new City(['name' => 'KwaMashu']),
            new City(['name' => 'La Lucia']),
            new City(['name' => 'La Mercy']),
            new City(['name' => 'Mount Edgecombe']),
            new City(['name' => 'New Germany']),
            new City(['name' => 'Pinetown']),
            new City(['name' => 'Queensburgh']),
            new City(['name' => 'Tongaat']),
            new City(['name' => 'Umbogintwini']),
            new City(['name' => 'Umdloti']),
            new City(['name' => 'Umgababa']),
            new City(['name' => 'Umhlanga']),
            new City(['name' => 'Umlazi']),
            new City(['name' => 'Verulam']),
            new City(['name' => 'Warner Beach']),
            new City(['name' => 'Westville']),
            new City(['name' => 'Winkelspruit']),
            new City(['name' => 'Chatsworth']),
            new City(['name' => 'Wentworth']),
            new City(['name' => 'Umkomaas']),
            new City(['name' => 'Magabeni']),
            new City(['name' => 'Phoenix']),
            new City(['name' => 'Ballito']),
            new City(['name' => 'KwaDukuza']),
            new City(['name' => 'Salt Rock']),
            new City(['name' => 'Bulwer']),
            new City(['name' => 'Franklin']),
            new City(['name' => 'Himeville']),
            new City(['name' => 'Ixopo']),
            new City(['name' => 'Kokstad']),
            new City(['name' => 'Matatiele']),
            new City(['name' => 'Swartberg']),
            new City(['name' => 'Umzimkulu']),
            new City(['name' => 'Underberg']),
            new City(['name' => 'Harding']),
            new City(['name' => 'Hibberdene']),
            new City(['name' => 'Ifafa Beach']),
            new City(['name' => 'Kelso']),
            new City(['name' => 'Margate']),
            new City(['name' => 'Palm Beach']),
            new City(['name' => 'Park Rynie']),
            new City(['name' => 'Pennington']),
            new City(['name' => 'Port Edward']),
            new City(['name' => 'Port Shepstone']),
            new City(['name' => 'Ramsgate']),
            new City(['name' => 'Scottburgh']),
            new City(['name' => 'Sezela']),
            new City(['name' => 'Shelly Beach']),
            new City(['name' => 'Southbroom']),
            new City(['name' => 'Umtentweni']),
            new City(['name' => 'Umzinto']),
            new City(['name' => 'Umzumbe']),
            new City(['name' => 'Uvongo']),
            new City(['name' => 'Balgowan']),
            new City(['name' => 'Boston']),
            new City(['name' => 'Byrne']),
            new City(['name' => 'Hilton']),
            new City(['name' => 'Howick']),
            new City(['name' => 'Merrivale']),
            new City(['name' => 'Mooi River']),
            new City(['name' => 'New Hanover']),
            new City(['name' => 'Pietermaritzburg - Capital']),
            new City(['name' => 'Richmond']),
            new City(['name' => 'Wartburg']),
            new City(['name' => 'Dalton']),
            new City(['name' => 'Hluhluwe']),
            new City(['name' => 'Ingwavuma']),
            new City(['name' => 'Mkuze']),
            new City(['name' => 'Mtubatuba']),
            new City(['name' => 'Ubombo']),
            new City(['name' => 'Jozini']),
            new City(['name' => 'Mbazwana']),
            new City(['name' => 'Manguzi']),
            new City(['name' => 'Dundee']),
            new City(['name' => 'Glencoe']),
            new City(['name' => 'Greytown']),
            new City(['name' => 'Kranskop']),
            new City(['name' => 'Muden']),
            new City(['name' => 'Pomeroy']),
            new City(['name' => 'Wasbank']),
            new City(['name' => 'Nquthu']),
            new City(['name' => 'Bergville']),
            new City(['name' => 'Colenso']),
            new City(['name' => 'Elandslaagte']),
            new City(['name' => 'Estcourt']),
            new City(['name' => 'Ladysmith']),
            new City(['name' => 'Weenen']),
            new City(['name' => 'Winterton']),
            new City(['name' => 'Babanango']),
            new City(['name' => 'Empangeni']),
            new City(['name' => 'Eshowe']),
            new City(['name' => 'Mandeni']),
            new City(['name' => 'Melmoth']),
            new City(['name' => 'Mtunzini']),
            new City(['name' => 'Richards Bay']),
            new City(['name' => 'Nkandla']),
            new City(['name' => 'Louwsburg']),
            new City(['name' => 'Mahlabatini']),
            new City(['name' => 'Nongoma']),
            new City(['name' => 'Paulpietersburg']),
            new City(['name' => 'Pongola']),
            new City(['name' => 'Ulundi']),
            new City(['name' => 'Vryheid']),
        ]);
    }

    /**
     * @param $mpn
     */
    public function MpnCities($mpn)
    {
        $mpn->cities()->saveMany([
            new City(['name' => 'Aankoms']),
            new City(['name' => 'Acornhoek']),
            new City(['name' => 'Amersfoort']),
            new City(['name' => 'Amsterdam']),
            new City(['name' => 'Anysspruit']),
            new City(['name' => 'Argent']),
            new City(['name' => 'Avoca']),
            new City(['name' => 'Avontuur']),
            new City(['name' => 'Badplaas']),
            new City(['name' => 'Balfour']),
            new City(['name' => 'Balmoral']),
            new City(['name' => 'Bankkop']),
            new City(['name' => 'Barberton']),
            new City(['name' => 'Belfast']),
            new City(['name' => 'Berbice']),
            new City(['name' => 'Bethal']),
            new City(['name' => 'Bettiesdam']),
            new City(['name' => 'Branddraai']),
            new City(['name' => 'Braunschweig']),
            new City(['name' => 'Breyten']),
            new City(['name' => 'Brondal']),
            new City(['name' => 'Bushbuckridge']),
            new City(['name' => 'Carolina']),
            new City(['name' => 'Chrissiesmeer']),
            new City(['name' => 'Davale']),
            new City(['name' => 'Delmas']),
            new City(['name' => 'Diepdale']),
            new City(['name' => 'Diepgezet']),
            new City(['name' => 'Dullstroom']),
            new City(['name' => 'Dundonald']),
            new City(['name' => 'Eerstehoek']),
            new City(['name' => 'Ekulindeni']),
            new City(['name' => 'Elukwatini']),
            new City(['name' => 'Embhuleni']),
            new City(['name' => 'Emphuluzi']),
            new City(['name' => 'Enkhaba']),
            new City(['name' => 'Ermelo']),
            new City(['name' => 'Fernie']),
            new City(['name' => 'Glenmore']),
            new City(['name' => 'Graskop']),
            new City(['name' => 'Greylingstad']),
            new City(['name' => 'Hartebeeskop']),
            new City(['name' => 'Hazyview']),
            new City(['name' => 'Hectorspruit']),
            new City(['name' => 'Kaapmuiden']),
            new City(['name' => 'Kinross']),
            new City(['name' => 'Komatipoort']),
            new City(['name' => 'KwaMhlanga']),
            new City(['name' => 'Lochiel']),
            new City(['name' => 'Loopspruit']),
            new City(['name' => 'Lydenburg']),
            new City(['name' => 'Machadodorp']),
            new City(['name' => 'Malelane']),
            new City(['name' => 'Marble Hall']),
            new City(['name' => 'Mbhejeka']),
            new City(['name' => 'Middelburg']),
            new City(['name' => 'Moddergat']),
            new City(['name' => 'Nelspruit']),
            new City(['name' => 'Ngodwana']),
            new City(['name' => 'Ohrigstad']),
            new City(['name' => 'Perdekop']),
            new City(['name' => 'Piet Retief']),
            new City(['name' => 'Pilgrims Rest']),
            new City(['name' => 'Sabie']),
            new City(['name' => 'Secunda']),
            new City(['name' => 'Siyabuswa']),
            new City(['name' => 'Skukuza']),
            new City(['name' => 'Standerton']),
            new City(['name' => 'Trichardt']),
            new City(['name' => 'Vaalbank']),
            new City(['name' => 'Volksrust']),
            new City(['name' => 'Wakkerstroom']),
            new City(['name' => 'Waterval Boven']),
            new City(['name' => 'Waterval Onder']),
            new City(['name' => 'White River']),
            new City(['name' => 'Witbank']),
        ]);
    }

    /**
     * @param $lmp
     */
    public function LmpCities($lmp)
    {
        $lmp->cities()->saveMany([
            new City(['name' => 'Afguns']),
            new City(['name' => 'Alldays']),
            new City(['name' => 'Bandelierkop']),
            new City(['name' => 'Ba-Phalaborwa']),
            new City(['name' => 'Bela-Bela']),
            new City(['name' => 'Bochum']),
            new City(['name' => 'Bosbokrand']),
            new City(['name' => 'Dendron']),
            new City(['name' => 'Duiwelskloof']),
            new City(['name' => 'Elim']),
            new City(['name' => 'Ellisras']),
            new City(['name' => 'Gravelotte']),
            new City(['name' => 'Haenertsburg']),
            new City(['name' => 'Hoedspruit']),
            new City(['name' => 'Klaserie']),
            new City(['name' => 'Lephalale']),
            new City(['name' => 'Letsitele']),
            new City(['name' => 'Leydsdorp']),
            new City(['name' => 'Louis Trichardt']),
            new City(['name' => 'Modimolle']),
            new City(['name' => 'Modjadjiskloof']),
            new City(['name' => 'Mogwadi']),
            new City(['name' => 'Mokopane']),
            new City(['name' => 'Mookgophong']),
            new City(['name' => 'Messina']),
            new City(['name' => 'Musina']),
            new City(['name' => 'Naboomspruit']),
            new City(['name' => 'Nylstroom']),
            new City(['name' => 'Ofcolaco']),
            new City(['name' => 'Phalaborwa']),
            new City(['name' => 'Polokwane']),
            new City(['name' => 'Potgietersrus']),
            new City(['name' => 'Roedtan']),
            new City(['name' => 'Senwabarwana']),
            new City(['name' => 'Seshego']),
            new City(['name' => 'Thabazimbi']),
            new City(['name' => 'Thohoyandou']),
            new City(['name' => 'Tzaneen']),
            new City(['name' => 'Vaalwater']),
            new City(['name' => 'Vivo']),
            new City(['name' => 'Zebedeila']),
            new City(['name' => 'Zion City Moria']),
        ]);
    }

    /**
     * @param $nw
     */
    public function NwCities($nw)
    {
        $nw->cities()->saveMany([
            new City(['name' => 'Amalia']),
            new City(['name' => 'Bray']),
            new City(['name' => 'Ganyesa']),
            new City(['name' => 'Mareetsane']),
            new City(['name' => 'Morokweng']),
            new City(['name' => 'Motlhabeng']),
            new City(['name' => 'Pampierstad']),
            new City(['name' => 'Reivilo']),
            new City(['name' => 'Schweizer-Reneke']),
            new City(['name' => 'Setlagole']),
            new City(['name' => 'Stella']),
            new City(['name' => 'Taung']),
            new City(['name' => 'Tosca']),
            new City(['name' => 'Vryburg']),
            new City(['name' => 'Setlopo']),
            new City(['name' => 'Babelegi']),
            new City(['name' => 'Beestekraal']),
            new City(['name' => 'Brits']),
            new City(['name' => 'Broederstroom']),
            new City(['name' => 'Derby']),
            new City(['name' => 'Ga-Rankuwa']),
            new City(['name' => 'Hartbeesfontein/Lethabong']),
            new City(['name' => 'Hartbeespoort']),
            new City(['name' => 'Hekpoort']),
            new City(['name' => 'Jericho']),
            new City(['name' => 'Kosmos']),
            new City(['name' => 'Koster']),
            new City(['name' => 'Kroondal']),
            new City(['name' => 'Maanhaarrand']),
            new City(['name' => 'Mabopane']),
            new City(['name' => 'Magaliesburg']),
            new City(['name' => 'Marikana']),
            new City(['name' => 'Mogwase']),
            new City(['name' => 'Mooinooi']),
            new City(['name' => 'Mathibestad']),
            new City(['name' => 'Ramokokastad']),
            new City(['name' => 'Rustenburg']),
            new City(['name' => 'Skeerpoort']),
            new City(['name' => 'Swartruggens']),
            new City(['name' => 'Tlhabane']),
            new City(['name' => 'Coligny']),
            new City(['name' => 'Delareyville']),
            new City(['name' => 'Ganyesa']),
            new City(['name' => 'Groot Marico']),
            new City(['name' => 'Lehurutshe']),
            new City(['name' => 'Lichtenburg']),
            new City(['name' => 'Mareetsane']),
            new City(['name' => 'Mahikeng']),
            new City(['name' => 'Mmabatho']),
            new City(['name' => 'Ottosdal']),
            new City(['name' => 'Ottoshoop']),
            new City(['name' => 'Sannieshof']),
            new City(['name' => 'Zeerust']),
            new City(['name' => 'Bloemhof']),
            new City(['name' => 'Christiana']),
            new City(['name' => 'Hartbeesfontein']),
            new City(['name' => 'Klerksdorp']),
            new City(['name' => 'Leeudoringstad']),
            new City(['name' => 'Makwassie']),
            new City(['name' => 'Orkney']),
            new City(['name' => 'Potchefstroom']),
            new City(['name' => 'Stilfontein']),
            new City(['name' => 'Ventersdorp']),
            new City(['name' => 'Wolmaransstad']),
        ]);
    }

    /**
     * @param $nc
     */
    public function NcCities($nc)
    {
        $nc->cities()->saveMany([
            new City(['name' => 'Barkly West']),
            new City(['name' => 'Campbell']),
            new City(['name' => 'Delportshoop']),
            new City(['name' => 'Douglas']),
            new City(['name' => 'Griquatown']),
            new City(['name' => 'Hartswater']),
            new City(['name' => 'Jan Kempdorp']),
            new City(['name' => 'Kimberley']),
            new City(['name' => 'Modder River']),
            new City(['name' => 'Warrenton']),
            new City(['name' => 'Windsorton']),
            new City(['name' => 'Andriesvale']),
            new City(['name' => 'Askham']),
            new City(['name' => 'Augrabies']),
            new City(['name' => 'Danielskuil']),
            new City(['name' => 'Groblershoop']),
            new City(['name' => 'Kakamas']),
            new City(['name' => 'Kanoneiland']),
            new City(['name' => 'Keimoes']),
            new City(['name' => 'Kenhardt']),
            new City(['name' => 'Lime Acres']),
            new City(['name' => 'Louisvale']),
            new City(['name' => 'Mier']),
            new City(['name' => 'Olifantshoek']),
            new City(['name' => 'Onseepkans']),
            new City(['name' => 'Postmasburg']),
            new City(['name' => 'Putsonderwater']),
            new City(['name' => 'Riemvasmaak']),
            new City(['name' => 'Upington']),
            new City(['name' => 'Aggeneys']),
            new City(['name' => 'Alexander Bay']),
            new City(['name' => 'Carolusberg']),
            new City(['name' => 'Concordia']),
            new City(['name' => 'Garies']),
            new City(['name' => 'Hondeklip']),
            new City(['name' => 'Kamieskroon']),
            new City(['name' => 'Kleinzee']),
            new City(['name' => 'Nababeep']),
            new City(['name' => 'Okiep']),
            new City(['name' => 'Pella']),
            new City(['name' => 'Pofadder']),
            new City(['name' => 'Port Nolloth']),
            new City(['name' => 'Soebatsfontein']),
            new City(['name' => 'Springbok']),
            new City(['name' => 'Steinkopf']),
            new City(['name' => 'Britstown']),
            new City(['name' => 'Colesberg']),
            new City(['name' => 'Copperton']),
            new City(['name' => 'De Aar']),
            new City(['name' => 'Hanover']),
            new City(['name' => 'Hopetown']),
            new City(['name' => 'Hutchinson']),
            new City(['name' => 'Loxton']),
            new City(['name' => 'Marydale']),
            new City(['name' => 'Norvalspont']),
            new City(['name' => 'Noupoort']),
            new City(['name' => 'Orania']),
            new City(['name' => 'Petrusville']),
            new City(['name' => 'Philipstown']),
            new City(['name' => 'Prieska']),
            new City(['name' => 'Richmond']),
            new City(['name' => 'Strydenburg']),
            new City(['name' => 'Vanderkloof']),
            new City(['name' => 'Victoria West']),
            new City(['name' => 'Vosburg']),
        ]);
    }

    /**
     * @param $wp
     */
    public function WpCities($wp)
    {
        $wp->cities()->saveMany([
            new City(['name' => 'Atlantis']),
            new City(['name' => 'Bellville']),
            new City(['name' => 'Blue Downs']),
            new City(['name' => 'Brackenfell']),
            new City(['name' => 'Cape Town']),
            new City(['name' => 'Crossroads']),
            new City(['name' => 'Durbanville']),
            new City(['name' => 'Eerste River']),
            new City(['name' => 'Elsies River']),
            new City(['name' => 'Fish Hoek']),
            new City(['name' => 'Goodwood']),
            new City(['name' => 'Gordons Bay']),
            new City(['name' => 'Guguletu']),
            new City(['name' => 'Hout Bay']),
            new City(['name' => 'Khayelitsha']),
            new City(['name' => 'Kraaifontein']),
            new City(['name' => 'Kuils River']),
            new City(['name' => 'Langa']),
            new City(['name' => 'Macassar']),
            new City(['name' => 'Melkbosstrand']),
            new City(['name' => 'Mfuleni']),
            new City(['name' => 'Milnerton']),
            new City(['name' => 'Mitchells Plain']),
            new City(['name' => 'Noordhoek']),
            new City(['name' => 'Nyanga']),
            new City(['name' => 'Observatory']),
            new City(['name' => 'Parow']),
            new City(['name' => 'Simons Town']),
            new City(['name' => 'Somerset West']),
            new City(['name' => 'Strand']),
            new City(['name' => 'Aurora']),
            new City(['name' => 'Bitterfontein']),
            new City(['name' => 'Chatsworth']),
            new City(['name' => 'Citrusdal']),
            new City(['name' => 'Clanwilliam']),
            new City(['name' => 'Darling']),
            new City(['name' => 'Doringbaai']),
            new City(['name' => 'Dwarskersbos']),
            new City(['name' => 'Ebenhaeser']),
            new City(['name' => 'Eendekuil']),
            new City(['name' => 'Elands Bay']),
            new City(['name' => 'Goedverwacht']),
            new City(['name' => 'Graafwater']),
            new City(['name' => 'Grotto Bay']),
            new City(['name' => 'Hopefield']),
            new City(['name' => 'Jacobsbaai']),
            new City(['name' => 'Jakkalsfontein']),
            new City(['name' => 'Kalbaskraal']),
            new City(['name' => 'Klawer']),
            new City(['name' => 'Koekenaap']),
            new City(['name' => 'Koringberg']),
            new City(['name' => 'Lamberts Bay']),
            new City(['name' => 'Langebaan']),
            new City(['name' => 'Langebaanweg']),
            new City(['name' => 'Lutzville']),
            new City(['name' => 'Malmesbury']),
            new City(['name' => 'Moorreesburg']),
            new City(['name' => 'Paternoster']),
            new City(['name' => 'Piketberg']),
            new City(['name' => 'Porterville']),
            new City(['name' => 'Redelinghuys']),
            new City(['name' => 'Riebeek-Kasteel']),
            new City(['name' => 'Riebeek West']),
            new City(['name' => 'Saldanha']),
            new City(['name' => 'St Helena Bay']),
            new City(['name' => 'Strandfontein']),
            new City(['name' => 'Vanrhynsdorp']),
            new City(['name' => 'Velddrif']),
            new City(['name' => 'Vredenburg']),
            new City(['name' => 'Vredendal']),
            new City(['name' => 'Wupperthal']),
            new City(['name' => 'Yzerfontein']),
            new City(['name' => 'Ashton']),
            new City(['name' => 'Bonnievale']),
            new City(['name' => 'Ceres']),
            new City(['name' => 'De Doorns']),
            new City(['name' => 'Denneburg']),
            new City(['name' => 'Franschhoek']),
            new City(['name' => 'Gouda']),
            new City(['name' => 'Kayamandi']),
            new City(['name' => 'Klapmuts']),
            new City(['name' => 'Kylemore']),
            new City(['name' => 'Languedoc']),
            new City(['name' => 'McGregor']),
            new City(['name' => 'Montagu']),
            new City(['name' => 'Op-die-Berg']),
            new City(['name' => 'Paarl']),
            new City(['name' => 'Pniel']),
            new City(['name' => 'Prince Alfred Hamlet']),
            new City(['name' => 'Rawsonville']),
            new City(['name' => 'Robertson']),
            new City(['name' => 'Robertsvlei']),
            new City(['name' => 'Rozendal']),
            new City(['name' => 'Saron']),
            new City(['name' => 'Stellenbosch']),
            new City(['name' => 'Touws River']),
            new City(['name' => 'Tulbagh']),
            new City(['name' => 'Wellington']),
            new City(['name' => 'Wemmershoek']),
            new City(['name' => 'Wolseley']),
            new City(['name' => 'Worcester']),
            new City(['name' => 'Arniston']),
            new City(['name' => 'Baardskeerdersbos']),
            new City(['name' => 'Barrydale']),
            new City(['name' => 'Bettys Bay']),
            new City(['name' => 'Birkenhead']),
            new City(['name' => 'Botrivier']),
            new City(['name' => 'Bredasdorp']),
            new City(['name' => 'Caledon']),
            new City(['name' => 'Dennehof']),
            new City(['name' => 'De Kelders']),
            new City(['name' => 'Elgin']),
            new City(['name' => 'Elim']),
            new City(['name' => 'Fisherhaven']),
            new City(['name' => 'Franskraalstrand']),
            new City(['name' => 'Gansbaai']),
            new City(['name' => 'Genadendal']),
            new City(['name' => 'Grabouw']),
            new City(['name' => 'Greyton']),
            new City(['name' => 'Hawston']),
            new City(['name' => 'Hermanus']),
            new City(['name' => 'Hotagterklip']),
            new City(['name' => 'Infanta']),
            new City(['name' => 'Kleinbaai']),
            new City(['name' => 'Kleinmond']),
            new City(['name' => 'LAgulhas']),
            new City(['name' => 'Napier']),
            new City(['name' => 'Onrusrivier']),
            new City(['name' => 'Pearly Beach']),
            new City(['name' => 'Pringle Bay']),
            new City(['name' => 'Riviersonderend']),
            new City(['name' => 'Rooi Els']),
            new City(['name' => 'Stanford']),
            new City(['name' => 'Struisbaai']),
            new City(['name' => 'Suiderstrand']),
            new City(['name' => 'Suurbraak']),
            new City(['name' => 'Swellendam']),
            new City(['name' => 'Van Dyksbaai']),
            new City(['name' => 'Vermont']),
            new City(['name' => 'Villiersdorp']),
            new City(['name' => 'Albertinia']),
            new City(['name' => 'Boggomsbaai']),
            new City(['name' => 'Brenton-on-Sea']),
            new City(['name' => 'Buffelsbaai']),
            new City(['name' => 'Calitzdorp']),
            new City(['name' => 'Dana Baai']),
            new City(['name' => 'De Rust']),
            new City(['name' => 'Dysselsdorp']),
            new City(['name' => 'Friemersheim']),
            new City(['name' => 'George']),
            new City(['name' => 'Glentana']),
            new City(['name' => 'Gouritsmond']),
            new City(['name' => 'Great Brak River']),
            new City(['name' => 'Groot-Jongensfontein']),
            new City(['name' => 'Haarlem']),
            new City(['name' => 'Hartenbos']),
            new City(['name' => 'Heidelberg']),
            new City(['name' => 'Herbertsdale']),
            new City(['name' => 'Herolds Bay']),
            new City(['name' => 'Keurboomsrivier']),
            new City(['name' => 'Keurboomstrand']),
            new City(['name' => 'Knysna']),
            new City(['name' => 'Kranshoek']),
            new City(['name' => 'Kurland Estate']),
            new City(['name' => 'Ladismith']),
            new City(['name' => 'Little Brak River']),
            new City(['name' => 'Mossel Bay']),
            new City(['name' => 'Natures Valley']),
            new City(['name' => 'Noetzie']),
            new City(['name' => 'Oudtshoorn']),
            new City(['name' => 'Pacaltsdorp']),
            new City(['name' => 'Plettenberg Bay']),
            new City(['name' => 'Port Beaufort']),
            new City(['name' => 'Rheenendal']),
            new City(['name' => 'Riversdale']),
            new City(['name' => 'Sedgefield']),
            new City(['name' => 'Slangrivier']),
            new City(['name' => 'Stilbaai']),
            new City(['name' => 'Uniondale']),
            new City(['name' => 'Volmoed']),
            new City(['name' => 'Victoria Bay']),
            new City(['name' => 'Wilderness']),
            new City(['name' => 'Wittedrift']),
            new City(['name' => 'Zoar']),
            new City(['name' => 'Beaufort West']),
            new City(['name' => 'Laingsburg']),
            new City(['name' => 'Leeu-Gamka']),
            new City(['name' => 'Matjiesfontein']),
            new City(['name' => 'Merweville']),
            new City(['name' => 'Murraysburg']),
            new City(['name' => 'Nelspoort']),
            new City(['name' => 'Prince Albert']),
        ]);
    }
}
